apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whisper-streaming
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-ingressn-nginxing-b14a263afc-c46cf3c3aab121af.elb.us-east-1.amazonaws.com # Use your LoadBalancer IP or domain
      http:
        paths:
          - path: /dashboard/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: whisper-streaming-raycluster-4f72n-head-svc
                port:
                  number: 8265
          - path: /serve/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: whisper-streaming-raycluster-4f72n-head-svc
                port:
                  number: 8000
