
SERVER_URL = "ws://127.0.0.1:8000/"  
# SERVER_URL = "wss://whisper-serve-public.jarvis.onebyzero.ai/"
AUDIO_FILE = "speech_dataset/sample_0000.wav"
SAMPLE_RATE = 16000
CHUNK_DURATION_MS = 400
SAMPLES_PER_CHUNK = int(SAMPLE_RATE * CHUNK_DURATION_MS / 1000)

REQUEST_TIMEOUT=3
AFTER_SENT_TIMEOUT=10
CHUNK_SLEEP=0.1
SILENCE_PADDING=2


SILENCE_THRESHOLD= 0.6
MIN_SPEECH_DURATION=0.5
MAX_BUFFER_DURATION=3000.0
BUFFER_CONTEXT=1.0
MODEL="deepdml/faster-whisper-large-v3-turbo-ct2"