---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: general
spec:
  template:
    metadata:
      labels:
        owner: obz-devops
        node-pool: general  
    spec: 
      nodeClassRef:
        name: general  
      taints:
        - key: node-pool
          value: general
          effect: NoSchedule               
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t2.xlarge","t2.2xlarge", "t3.large", "t3.xlarge", "t3.2xlarge"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-1a", "us-east-1b", "us-east-1c"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type # If not included, the webhook for the AWS cloud provider will default to on-demand
          operator: In
          values: ["on-demand"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    #consolidateAfter: 1800s
    expireAfter: 720h    
  limits:
    cpu: "1000"
    memory: 1000Gi          

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: general
spec:
  amiFamily: Bottlerocket 
  instanceProfile: "jarvis-kuberay-cluster-worker-i" 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "jarvis-kuberay-cluster" 
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "jarvis-kuberay-cluster"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 4Gi
        deleteOnTermination: true
        # encrypted: true
        # kmsKeyID: "f019a451-b9e5-4286-9fa7-308f7feb8cee"           
    # Bottlerocket data volume
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: 20Gi
        deleteOnTermination: true   
        # encrypted: true
        # kmsKeyID: "f019a451-b9e5-4286-9fa7-308f7feb8cee"          
  # Optional, configures IMDS for the instance
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  tags:
    cost-profile: jarvis-kuberay-cluster            